-- MySQL Script generated by MySQL Workbench
-- Sat Oct  3 14:53:56 2026
-- Model: New Model    Version: 5.0.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`statusCex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statusCex` (
  `idStatusCex` INT NOT NULL AUTO_INCREMENT,
  `statusCex` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatusCex`),
  UNIQUE INDEX `statusCex_UNIQUE` (`statusCex` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cex` (
  `idCex` INT NOT NULL AUTO_INCREMENT,
  `idStatusCex` INT NOT NULL DEFAULT 1,
  `nazvanieCexa` VARCHAR(45) NOT NULL,
  `korpus` INT NOT NULL,
  PRIMARY KEY (`idCex`),
  INDEX `fk_cex_statusCex1_idx` (`idStatusCex` ASC) VISIBLE,
  CONSTRAINT `fk_cex_statusCex1`
    FOREIGN KEY (`idStatusCex`)
    REFERENCES `mydb`.`statusCex` (`idStatusCex`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `chk_cex_korpus` CHECK (`korpus` > 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipOborudovanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipOborudovanie` (
  `idTipOborudovanie` INT NOT NULL AUTO_INCREMENT,
  `tipOborudovanie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipOborudovanie`),
  UNIQUE INDEX `tipOborudovanie_UNIQUE` (`tipOborudovanie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`statusOborudovanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statusOborudovanie` (
  `idStatusOborudovanie` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatusOborudovanie`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oborudovanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`oborudovanie` (
  `idOborudovanie` INT NOT NULL AUTO_INCREMENT,
  `idCex` INT NOT NULL,
  `idStatusOborudovanie` INT NOT NULL DEFAULT 1,
  `idTipOborudovanie` INT NOT NULL,
  `naimenovanie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOborudovanie`),
  INDEX `fk_oborudovanie_cex1_idx` (`idCex` ASC) VISIBLE,
  INDEX `fk_oborudovanie_tipOborudovanie1_idx` (`idTipOborudovanie` ASC) VISIBLE,
  INDEX `fk_oborudovanie_statusOborudovanie1_idx` (`idStatusOborudovanie` ASC) VISIBLE,
  CONSTRAINT `fk_oborudovanie_cex1`
    FOREIGN KEY (`idCex`)
    REFERENCES `mydb`.`cex` (`idCex`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_oborudovanie_tipOborudovanie1`
    FOREIGN KEY (`idTipOborudovanie`)
    REFERENCES `mydb`.`tipOborudovanie` (`idTipOborudovanie`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_oborudovanie_statusOborudovanie1`
    FOREIGN KEY (`idStatusOborudovanie`)
    REFERENCES `mydb`.`statusOborudovanie` (`idStatusOborudovanie`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recept` (
  `idRecept` INT NOT NULL AUTO_INCREMENT,
  `nazvanieRecepta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRecept`),
  UNIQUE INDEX `nazvanieRecepta_UNIQUE` (`nazvanieRecepta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipKirpicha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipKirpicha` (
  `idKirpich` INT NOT NULL AUTO_INCREMENT,
  `idRecept` INT NOT NULL,
  `nazvanieKirpicha` VARCHAR(45) NOT NULL,
  `markaKirpicha` VARCHAR(45) NOT NULL,
  `sizeKirpicha` VARCHAR(45) NOT NULL,
  `massaKirpicha` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`idKirpich`),
  INDEX `fk_tipKirpicha_recept1_idx` (`idRecept` ASC) VISIBLE,
  CONSTRAINT `fk_tipKirpicha_recept1`
    FOREIGN KEY (`idRecept`)
    REFERENCES `mydb`.`recept` (`idRecept`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `chk_kirpich_massa` CHECK (`massaKirpicha` > 1 and `massaKirpicha` < 7))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan` (
  `idPlan` INT NOT NULL AUTO_INCREMENT,
  `dataNachala` DATETIME NOT NULL,
  `dataOkonchaniya` DATETIME NOT NULL,
  PRIMARY KEY (`idPlan`),
  CONSTRAINT `chk_plan_dates` CHECK (`dataOkonchaniya` >= `dataNachala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proizvodstvennayaPartiya`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proizvodstvennayaPartiya` (
  `idPartiya` INT NOT NULL AUTO_INCREMENT,
  `idPlan` INT NOT NULL,
  `idKirpich` INT NOT NULL,
  `dataProizvodstva` DATETIME NOT NULL,
  `colProducta` INT NOT NULL,
  PRIMARY KEY (`idPartiya`),
  INDEX `fk_proizvodstvennayaPartiya_plan1_idx` (`idPlan` ASC) VISIBLE,
  INDEX `fk_proizvodstvennayaPartiya_kirpich1_idx` (`idKirpich` ASC) VISIBLE,
  CONSTRAINT `fk_proizvodstvennayaPartiya_plan1`
    FOREIGN KEY (`idPlan`)
    REFERENCES `mydb`.`plan` (`idPlan`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_proizvodstvennayaPartiya_kirpich1`
    FOREIGN KEY (`idKirpich`)
    REFERENCES `mydb`.`tipKirpicha` (`idKirpich`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `chk_partiya_col` CHECK (`colProducta` > 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vidBraka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vidBraka` (
  `idVidBraka` INT NOT NULL AUTO_INCREMENT,
  `vidBraka` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idVidBraka`),
  UNIQUE INDEX `vidBraka_UNIQUE` (`vidBraka` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brak` (
  `idBrak` INT NOT NULL AUTO_INCREMENT,
  `idPartiya` INT NOT NULL,
  `idVidBraka` INT NOT NULL,
  `prichinaBraka` VARCHAR(255) NOT NULL,
  `colBraka` INT NOT NULL,
  PRIMARY KEY (`idBrak`),
  INDEX `fk_brak_proizvodstvennayaPartiya1_idx` (`idPartiya` ASC) VISIBLE,
  INDEX `fk_brak_vidBraka1_idx` (`idVidBraka` ASC) VISIBLE,
  CONSTRAINT `fk_brak_proizvodstvennayaPartiya1`
    FOREIGN KEY (`idPartiya`)
    REFERENCES `mydb`.`proizvodstvennayaPartiya` (`idPartiya`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_brak_vidBraka1`
    FOREIGN KEY (`idVidBraka`)
    REFERENCES `mydb`.`vidBraka` (`idVidBraka`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `chk_brak_col` CHECK (`colBraka` > 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dolzhnost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dolzhnost` (
  `idDolzhnost` INT NOT NULL AUTO_INCREMENT,
  `dolzhnost` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDolzhnost`),
  UNIQUE INDEX `dolzhnost_UNIQUE` (`dolzhnost` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal` (
  `idPersonal` INT NOT NULL AUTO_INCREMENT,
  `idDolzhnost` INT NOT NULL,
  `familiya` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `otchestvo` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersonal`),
  INDEX `fk_personal_dolzhnost1_idx` (`idDolzhnost` ASC) VISIBLE,
  CONSTRAINT `fk_personal_dolzhnost1`
    FOREIGN KEY (`idDolzhnost`)
    REFERENCES `mydb`.`dolzhnost` (`idDolzhnost`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vidNormativDocument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vidNormativDocument` (
  `idVidNormativDocument` INT NOT NULL AUTO_INCREMENT,
  `vidNormativDocument` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVidNormativDocument`),
  UNIQUE INDEX `vidNormativDocument_UNIQUE` (`vidNormativDocument` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`statusNormativDocument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statusNormativDocument` (
  `idStatusNormativDocument` INT NOT NULL AUTO_INCREMENT,
  `statusNormativDocument` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatusNormativDocument`),
  UNIQUE INDEX `statusNormativDocument_UNIQUE` (`statusNormativDocument` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`normativDocument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`normativDocument` (
  `idNormativDocument` INT NOT NULL AUTO_INCREMENT,
  `idVidNormativDocument` INT NOT NULL,
  `idStatusNormativDocument` INT NOT NULL,
  `nazvanieNormativDoc` VARCHAR(255) NOT NULL,
  `nomerDocumenta` VARCHAR(45) NOT NULL,
  `dataSozdaniya` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idNormativDocument`),
  INDEX `fk_normativDocument_vidNormativDocument1_idx` (`idVidNormativDocument` ASC) VISIBLE,
  INDEX `fk_normativDocument_statusNormativDocument1_idx` (`idStatusNormativDocument` ASC) VISIBLE,
  UNIQUE INDEX `nomerDocumenta_UNIQUE` (`nomerDocumenta` ASC) VISIBLE,
  CONSTRAINT `fk_normativDocument_vidNormativDocument1`
    FOREIGN KEY (`idVidNormativDocument`)
    REFERENCES `mydb`.`vidNormativDocument` (`idVidNormativDocument`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_normativDocument_statusNormativDocument1`
    FOREIGN KEY (`idStatusNormativDocument`)
    REFERENCES `mydb`.`statusNormativDocument` (`idStatusNormativDocument`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vidKontrolyaProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vidKontrolyaProd` (
  `idVidKontrolya` INT NOT NULL AUTO_INCREMENT,
  `vidKontrolya` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVidKontrolya`),
  UNIQUE INDEX `vidKontrolya_UNIQUE` (`vidKontrolya` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rezultatProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rezultatProd` (
  `idRezultatProd` INT NOT NULL AUTO_INCREMENT,
  `rezultatProd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRezultatProd`),
  UNIQUE INDEX `rezultatProd_UNIQUE` (`rezultatProd` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kontrolProducta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kontrolProducta` (
  `idKontrolProducta` INT NOT NULL AUTO_INCREMENT,
  `idNormativDocument` INT NOT NULL,
  `idVidKontrolyaProd` INT NOT NULL,
  `idPartiya` INT NOT NULL,
  `dataProverki` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `norma` VARCHAR(45) NOT NULL,
  `factZnachenie` DECIMAL(10,3) NOT NULL,
  `idRezultatProd` INT NOT NULL,
  PRIMARY KEY (`idKontrolProducta`),
  INDEX `fk_kontrolProducta_normativDocument1_idx` (`idNormativDocument` ASC) VISIBLE,
  INDEX `fk_kontrolProducta_proizvodstvennayaPartiya1_idx` (`idPartiya` ASC) VISIBLE,
  INDEX `fk_kontrolProducta_vidKontrolyaProd1_idx` (`idVidKontrolyaProd` ASC) VISIBLE,
  INDEX `fk_kontrolProducta_rezultatProd1_idx` (`idRezultatProd` ASC) VISIBLE,
  CONSTRAINT `fk_kontrolProducta_normativDocument1`
    FOREIGN KEY (`idNormativDocument`)
    REFERENCES `mydb`.`normativDocument` (`idNormativDocument`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_kontrolProducta_proizvodstvennayaPartiya1`
    FOREIGN KEY (`idPartiya`)
    REFERENCES `mydb`.`proizvodstvennayaPartiya` (`idPartiya`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_kontrolProducta_vidKontrolyaProd1`
    FOREIGN KEY (`idVidKontrolyaProd`)
    REFERENCES `mydb`.`vidKontrolyaProd` (`idVidKontrolya`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_kontrolProducta_rezultatProd1`
    FOREIGN KEY (`idRezultatProd`)
    REFERENCES `mydb`.`rezultatProd` (`idRezultatProd`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vidSiryo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vidSiryo` (
  `idVidSiryo` INT NOT NULL AUTO_INCREMENT,
  `vidSiryo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVidSiryo`),
  UNIQUE INDEX `vidSiryo_UNIQUE` (`vidSiryo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colMateriala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`colMateriala` (
  `idColMateriala` INT NOT NULL AUTO_INCREMENT,
  `idRecept` INT NOT NULL,
  `idVidSiryo` INT NOT NULL,
  `colMateriala` DECIMAL(12,2) NOT NULL,
  `edIzmereniya` VARCHAR(45) NOT NULL DEFAULT 'кг / 1000 шт',
  PRIMARY KEY (`idColMateriala`),
  INDEX `fk_colMateriala_recept1_idx` (`idRecept` ASC) VISIBLE,
  INDEX `fk_colMateriala_vidSiryo1_idx` (`idVidSiryo` ASC) VISIBLE,
  CONSTRAINT `fk_colMateriala_recept1`
    FOREIGN KEY (`idRecept`)
    REFERENCES `mydb`.`recept` (`idRecept`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_colMateriala_vidSiryo1`
    FOREIGN KEY (`idVidSiryo`)
    REFERENCES `mydb`.`vidSiryo` (`idVidSiryo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `chk_material_col` CHECK (`colMateriala` > 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ispolzovanieOborudovaniya`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ispolzovanieOborudovaniya` (
  `idIspolzovanieOborudovaniya` INT NOT NULL AUTO_INCREMENT,
  `idPartiya` INT NOT NULL,
  `idOborudovanie` INT NOT NULL,
  `timeNachala` DATETIME NOT NULL,
  `timeOkonchaniya` DATETIME NOT NULL,
  PRIMARY KEY (`idIspolzovanieOborudovaniya`),
  INDEX `fk_ispolzovanieOborudovanie_proizvodstvennayaPartiya1_idx` (`idPartiya` ASC) VISIBLE,
  INDEX `fk_ispolzovanieOborudovanie_oborudovanie1_idx` (`idOborudovanie` ASC) VISIBLE,
  CONSTRAINT `fk_ispolzovanieOborudovanie_proizvodstvennayaPartiya1`
    FOREIGN KEY (`idPartiya`)
    REFERENCES `mydb`.`proizvodstvennayaPartiya` (`idPartiya`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ispolzovanieOborudovanie_oborudovanie1`
    FOREIGN KEY (`idOborudovanie`)
    REFERENCES `mydb`.`oborudovanie` (`idOborudovanie`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `chk_ispolz_dates` CHECK (`timeOkonchaniya` > `timeNachala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rabotaPersonala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rabotaPersonala` (
  `idRabotaPersonala` INT NOT NULL AUTO_INCREMENT,
  `idPersonal` INT NOT NULL,
  `idPartiya` INT NOT NULL,
  `timeNachala` DATETIME NOT NULL,
  `timeOkonchaniya` DATETIME NOT NULL,
  PRIMARY KEY (`idRabotaPersonala`),
  INDEX `fk_rabotaPersonala_proizvodstvennayaPartiya1_idx` (`idPartiya` ASC) VISIBLE,
  INDEX `fk_rabotaPersonala_personal1_idx` (`idPersonal` ASC) VISIBLE,
  CONSTRAINT `fk_rabotaPersonala_proizvodstvennayaPartiya1`
    FOREIGN KEY (`idPartiya`)
    REFERENCES `mydb`.`proizvodstvennayaPartiya` (`idPartiya`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rabotaPersonala_personal1`
    FOREIGN KEY (`idPersonal`)
    REFERENCES `mydb`.`personal` (`idPersonal`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `chk_rabota_dates` CHECK (`timeOkonchaniya` > `timeNachala`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
